### ISSUE TITLE
전통주점을 클릭했을때 redirect

### ISSUE THREAD

**Issue by byh9811** [byh9811/traditional-liquor-recommendation-service#3]
절대경로로 페이지를 띄워줘야 하는데 상대경로로 이동해서 404에러가 발생함.

**Comment by byh9811** [comment]
대충 검색해보니까 Link 말고 a태그 써야한다 하던데 확인해봐.
참고: https://velog.io/@syoo970/React-Router-Dom%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%84%9C-%EC%99%B8%EB%B6%80-%EB%A7%81%ED%81%AC%EB%A1%9C-redirect-%EC%8B%9C%ED%82%A4%EA%B8%B0V6

**Comment by jisung24** [comment]
finished..
